### PR TITLE
Feature/pi email

### PR DESCRIPTION
**Pull request by sagun98**
Small additional patch
jdrf/pages/templates/upload_metadata.html
Line no: 133 
Currently, having more than 1word in PI name fails the validation.
Updated the regex to support multiple words during metadata form submission .

### CODE REVIEW

**Comment by sagun98** [comment]
Updated the Pull request for the changes last discussed. Please review it when you get the chance @ljmciver . The last 2 commits are the new ones though it is showing '8 days ago.'

**Comment by ljmciver** [comment]
@sagun98 Thanks for the changes! I think just a couple small changes and we are set!
1. It looks like the case on the variable in the email function are a bit different then the existing variable name. EMAIL_to needs to be changed to EMAIL_TO.
2. I think the changes for the cc in the email function might need to be a bit different. I was not able to find the exact spec in the python module docs but did find some notes on stackoverflow: https://stackoverflow.com/questions/8856117/how-to-send-email-to-multiple-recipients-using-python-smtplib/12422921 .
3. The folder with the metadata files needs to be changed slightly to include "_uploaded" at the end of the folder name.

Please let me know if you have any questions!
Thanks!
Lauren

**Comment by sagun98** [comment]
Hi @ljmciver . 
1. EMAIL_to was updated to EMAIL_TO. Additional, mail_to list was updated to have PI_email, user_email and jdrf developer group email under conditions. 
2. '_uploaded' was added to the path of archive metadatastudy.tsv file. 

Additionally, guinicorn server needs to be restarted after merging this change as the schema will still be expecting 14 rows while we have 15 total rows(New row: PI Email) and will fail the metadata validation. However, running 'supervisorctl restart gunicorn' resolves this issue.

**Comment by ljmciver** [comment]
Thank you, @sagun98 !

**Pull request merged**
